/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

#define IOCON_PIO_ASW_DI 0x00u        /*!<@brief Analog switch is open (disabled) */
#define IOCON_PIO_ASW_EN 0x0400u      /*!<@brief Analog switch is closed (enabled) */
#define IOCON_PIO_DIGITAL_EN 0x0100u  /*!<@brief Enables digital function */
#define IOCON_PIO_FUNC0 0x00u         /*!<@brief Selects pin function 0 */
#define IOCON_PIO_FUNC6 0x06u         /*!<@brief Selects pin function 6 */
#define IOCON_PIO_INV_DI 0x00u        /*!<@brief Input function is not inverted */
#define IOCON_PIO_MODE_INACT 0x00u    /*!<@brief No addition pin function */
#define IOCON_PIO_MODE_PULLUP 0x20u   /*!<@brief Selects pull-up function */
#define IOCON_PIO_OPENDRAIN_DI 0x00u  /*!<@brief Open drain is disabled */
#define IOCON_PIO_SLEW_STANDARD 0x00u /*!<@brief Standard mode, output slew rate control is enabled */

/*! @name SWO (number 21), J9[1]/U18[12]/N4M_SWO
  @{ */
/* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins(void); /* Function assigned for the Cortex-M33 */

#define IOCON_PIO_DIGITAL_EN 0x0100u  /*!<@brief Enables digital function */
#define IOCON_PIO_FUNC0 0x00u         /*!<@brief Selects pin function 0 */
#define IOCON_PIO_FUNC1 0x01u         /*!<@brief Selects pin function 1 */
#define IOCON_PIO_INV_DI 0x00u        /*!<@brief Input function is not inverted */
#define IOCON_PIO_MODE_PULLDOWN 0x10u /*!<@brief Selects pull-down function */
#define IOCON_PIO_MODE_PULLUP 0x20u   /*!<@brief Selects pull-up function */
#define IOCON_PIO_OPENDRAIN_DI 0x00u  /*!<@brief Open drain is disabled */
#define IOCON_PIO_SLEW_STANDARD 0x00u /*!<@brief Standard mode, output slew rate control is enabled */

/*! @name PIO1_4 (number 1), Q5[G1]/J12[6]/ARD_LEDR_PWM
  @{ */
#define MANAGE_EVK_IO_OPTIMIZATION_LED_RED_GPIO GPIO /*!<@brief GPIO device name: GPIO */
#define MANAGE_EVK_IO_OPTIMIZATION_LED_RED_PORT 1U   /*!<@brief PORT device name: 1U */
#define MANAGE_EVK_IO_OPTIMIZATION_LED_RED_PIN 4U    /*!<@brief 1U pin index: 4 */
                                                     /* @} */

/*! @name PIO1_6 (number 5), Q4[G1]/J12[10]/ARD_LEDB_PWM
  @{ */
#define MANAGE_EVK_IO_OPTIMIZATION_LED_BLUE_GPIO GPIO /*!<@brief GPIO device name: GPIO */
#define MANAGE_EVK_IO_OPTIMIZATION_LED_BLUE_PORT 1U   /*!<@brief PORT device name: 1U */
#define MANAGE_EVK_IO_OPTIMIZATION_LED_BLUE_PIN 6U    /*!<@brief 1U pin index: 6 */
                                                      /* @} */

/*! @name PIO1_7 (number 9), Q4[G2]/J12[8]/ARD_LEDG_PWM
  @{ */
#define MANAGE_EVK_IO_OPTIMIZATION_LED_GREEN_GPIO GPIO /*!<@brief GPIO device name: GPIO */
#define MANAGE_EVK_IO_OPTIMIZATION_LED_GREEN_PORT 1U   /*!<@brief PORT device name: 1U */
#define MANAGE_EVK_IO_OPTIMIZATION_LED_GREEN_PIN 7U    /*!<@brief 1U pin index: 7 */
                                                       /* @} */

/*! @name FC0_RXD_SDA_MOSI_DATA (number 92), U11[14]/U22[14]/FC0_USART_RXD
  @{ */
/* @} */

/*! @name FC0_TXD_SCL_MISO_WS (number 94), U11[13]/U22[13]/FC0_USART_TXD
  @{ */
/* @} */

/*! @name PIO0_19 (number 90), U13[30]/J9[11]/FC7_I2S_WS
  @{ */
#define MANAGE_EVK_IO_OPTIMIZATION_FC7_I2S_WS_GPIO GPIO /*!<@brief GPIO device name: GPIO */
#define MANAGE_EVK_IO_OPTIMIZATION_FC7_I2S_WS_PORT 0U   /*!<@brief PORT device name: 0U */
#define MANAGE_EVK_IO_OPTIMIZATION_FC7_I2S_WS_PIN 19U   /*!<@brief 0U pin index: 19 */
                                                        /* @} */

/*! @name PIO0_20 (number 74), J19[2]/J9[9]/FC7_I2S_TX
  @{ */
#define MANAGE_EVK_IO_OPTIMIZATION_FC7_I2S_TX_GPIO GPIO /*!<@brief GPIO device name: GPIO */
#define MANAGE_EVK_IO_OPTIMIZATION_FC7_I2S_TX_PORT 0U   /*!<@brief PORT device name: 0U */
#define MANAGE_EVK_IO_OPTIMIZATION_FC7_I2S_TX_PIN 20U   /*!<@brief 0U pin index: 20 */
                                                        /* @} */

/*! @name PIO0_21 (number 76), U13[29]/J9[13]/FC7_I2S_BCLK
  @{ */
#define MANAGE_EVK_IO_OPTIMIZATION_FC7_I2S_BCLK_GPIO GPIO /*!<@brief GPIO device name: GPIO */
#define MANAGE_EVK_IO_OPTIMIZATION_FC7_I2S_BCLK_PORT 0U   /*!<@brief PORT device name: 0U */
#define MANAGE_EVK_IO_OPTIMIZATION_FC7_I2S_BCLK_PIN 21U   /*!<@brief 0U pin index: 21 */
                                                          /* @} */

/*! @name PIO1_13 (number 2), J18[2]/J9[19]/FC6_I2S_RX
  @{ */
#define MANAGE_EVK_IO_OPTIMIZATION_FC6_I2S_RX_GPIO GPIO /*!<@brief GPIO device name: GPIO */
#define MANAGE_EVK_IO_OPTIMIZATION_FC6_I2S_RX_PORT 1U   /*!<@brief PORT device name: 1U */
#define MANAGE_EVK_IO_OPTIMIZATION_FC6_I2S_RX_PIN 13U   /*!<@brief 1U pin index: 13 */
                                                        /* @} */

/*! @name PIO1_31 (number 91), J13[7]/J13[8]/U13[28]/I2S_MCLK
  @{ */
#define MANAGE_EVK_IO_OPTIMIZATION_I2S_MCLK_GPIO GPIO /*!<@brief GPIO device name: GPIO */
#define MANAGE_EVK_IO_OPTIMIZATION_I2S_MCLK_PORT 1U   /*!<@brief PORT device name: 1U */
#define MANAGE_EVK_IO_OPTIMIZATION_I2S_MCLK_PIN 31U   /*!<@brief 1U pin index: 31 */
                                                      /* @} */

/*! @name PIO1_22 (number 41), U25[3]/CAN_RXD
  @{ */
#define MANAGE_EVK_IO_OPTIMIZATION_CAN_RXD_GPIO GPIO /*!<@brief GPIO device name: GPIO */
#define MANAGE_EVK_IO_OPTIMIZATION_CAN_RXD_PORT 1U   /*!<@brief PORT device name: 1U */
#define MANAGE_EVK_IO_OPTIMIZATION_CAN_RXD_PIN 22U   /*!<@brief 1U pin index: 22 */
                                                     /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void manage_evk_io_optimization(void); /* Function assigned for the Cortex-M33 */

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
